import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/pages/componets/Header'
import Banner from './componets/Banner'
import SlidShow from './componets/SlideShow'
import HoiseFill from './componets/ComponetsHouse'
import InfiniteScroll from 'react-infinite-scroll-component';
import Footer from './componets/Footer'
import Model from './componets/Model'
import RgisterModel from './componets/Model/RegisterModel'
import UseRegisterModel from './api/hooks/UseRegisterModel'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const fetchMoreData = () => {
    // Cette fonction sera appelée lors du défilement pour charger plus de données
    // Ici, vous pouvez mettre à jour votre état pour ajouter plus de contenu
  };

  const {isOpen, onClose} = UseRegisterModel();
  return (
    <>
      <Head>
        <title>Airbnb clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
     <RgisterModel visibel={isOpen}  onClose={onClose}/>
     {/* Header */}

     <Header />

     {/* Banner */}

     
     <div className='mt-11'>
     <SlidShow />
     </div>

     <main className='max-w-7xl mx-auto px-8 sm:px-16'>
      <section className='pt-6'>
      <div className="grid grid-cols-1  sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-4  gap-7"> {/* Conteneur pour les composants HoiseFill */}
            <HoiseFill image='https://a0.muscache.com/im/pictures/prohost-api/Hosting-664986945014341209/original/193d04c2-635b-41ef-85d6-0ee963127451.jpeg?im_w=720'  location='faro/Portugal' type='Profssionelle' prix={187}/>
            <HoiseFill image='https://a0.muscache.com/im/pictures/prohost-api/Hosting-778635943408232000/original/015538ab-5caa-4fd7-bef6-d8493e5f7c80.jpeg?im_w=720' location='Grenade/Espagne' type='Professionelle'prix={187}/>
            {/* Vous pouvez ajouter d'autres instances de HoiseFill ici */}
            <HoiseFill image='https://a0.muscache.com/im/pictures/9f9b302c-34d7-4da7-83bc-42f774bc6723.jpg?im_w=720'  location='faro/Portugal' type='Profssionelle'prix={187}/>
            <HoiseFill image='https://a0.muscache.com/im/pictures/miso/Hosting-52839461/original/20280b64-2b90-4e95-ba3d-55d3fd11f5d8.jpeg?im_w=720' location='Grenade/Espagne' type='Professionelle' prix={187}/>
            <HoiseFill image='https://a0.muscache.com/im/pictures/miso/Hosting-671515411169755702/original/8b49f068-8902-4d4d-84bf-b501cf59a448.jpeg?im_w=720'  location='faro/Portugal' type='Profssionelle' prix={187}/>
            <HoiseFill image='https://a0.muscache.com/im/pictures/239b7ed7-6f74-4591-b0d4-572336e1f174.jpg?im_w=720' location='Grenade/Espagne' type='Professionelle' prix={187}/>
          

          
            <HoiseFill image='https://a0.muscache.com/im/pictures/52159509/5acc860d_original.jpg?im_w=720'  location='faro/Portugal' type='Profssionelle' prix={187}/>
            <HoiseFill image='https://a0.muscache.com/im/pictures/miso/Hosting-742424658135898180/original/ef5464ea-5eb8-426a-a097-a4ed7a395610.jpeg?im_w=720' location='Grenade/Espagne' type='Professionelle' prix={187}/>
          
            <HoiseFill image='https://a0.muscache.com/im/pictures/e9b6dd85-7b1d-4b27-9512-2dbd00e55402.jpg?im_w=720'  location='faro/Portugal' type='Profssionelle' prix={187}/>
            <HoiseFill image='https://a0.muscache.com/im/pictures/prohost-api/Hosting-48509375/original/0862735b-4abc-4d87-a8d1-f2fb6053adc8.jpeg?im_w=720' location='Grenade/Espagne' type='Professionelle' prix={187}/>
          
          </div>
          
      </section>

      <div className='mt-20'>
        <Footer />
      </div>
     </main>
     
     
     
     
    </>
  )
}